# My configuration for FireFace UCX headphone volume
# Shift + Volume Up/Down/Mute keys
# Blue volume bar in lower right screen corner on a 1440p display

config.ini

[Hotkeys]
VolumeUpHotkey=+Volume_Up
VolumeDownHotkey=+Volume_Down
VolumeMuteHotkey=+Volume_Mute

# Aus dem Fireface UCX Manual
# Das Format für die Control-Change-Befehle ist:
# Bx yy zz
# x = MIDI channel
# yy = control number
# zz = value
# Die erste Reihe in TotalMix wird adressiert über MIDI Kanäle 1 bis 4, Reihe 2 über Kanäle 5 bis
# 8 und Reihe 3 über Kanäle 9 bis 12.
# Benutzt werden 16 Controller-Nummern, und zwar die Nummern 102 bis 117 (= hex 66 bis 75).
# Mit diesen 16 Controllern (= Fadern) und jeweils 4 MIDI-Kanälen pro Reihe lassen sich bis zu
# 64 Fader pro Reihe adressieren (wie es bei der HDSPe MADI erforderlich ist).
# Anwendungsbeispiele zum Senden von MIDI-Befehlszeilen:
# - Input 1 auf 0 dB setzen: B0 66 68
# - Input 17 auf maximale Absenkung setzen: B1 66 0
# - Playback 1 auf Maximum setzen: B4 66 7F
# - Output 16 auf 0 dB setzen: B8 75 68
#
# Damit ist beim Fireface UCX Main der MIDI Channel für die untere Reihe 9
# PH ist CC 108, Main CC 102 (offenbar geht es in Zweierschritten [logisch weil stereo, könnte man ja auch als mono konfigurieren],
# und Main ist AN 1/2, auch wenn es ganz rechts angeordnet ist)

[Midiport]
DeviceName=loopMIDI Port
MidiChannel=9
MidiCC=108

[Volume]
MaxValue=127
LastValue=36
VolumeStep=4

[Settings]
HideTrayIcon=0

[OSD]
DisplayTime=2000
Color=4fedff
BackgroundColor=212b32
PosX=2294
PosY=1350
Width=200
Height=24
