name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:

jobs:

  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Version
        run: |
          $GIT_TAG = git describe --tags
          echo "Version: $GIT_TAG"
          echo "GIT_TAG=$GIT_TAG" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@v1.1.0
        with:
          in: TotalKeyMix.ahk
          icon: icon.ico

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TotalKeyMix_${{env.GIT_TAG}}
          path: |
            TotalKeyMix.exe
            config.ini
